### ISSUE TITLE
Vẽ class diagrams

### ISSUE THREAD

**Issue by toan203ha** [toan203ha/Nhom3_T2_Ca1_QuanLiNhaSach#3]
Hoàn thành Vẽ class diagrams

**Comment by Chiphub123** [comment]
[Nhom3_t2_c1_quanlynhasach.docx](https://github.com/toan203ha/Nhom3_T2_Ca1_QuanLiNhaSach/files/11245231/Nhom3_t2_c1_quanlynhasach.docx)

**Comment by Chiphub123** [comment]
Solve #1 
[Nhom3_t2_c1_quanlynhasach.docx](https://github.com/toan203ha/Nhom3_T2_Ca1_QuanLiNhaSach/files/11245245/Nhom3_t2_c1_quanlynhasach.docx)
