### ISSUE TITLE
Vẽ activity diagrams

### ISSUE THREAD

**Issue by toan203ha** [toan203ha/Nhom3_T2_Ca1_QuanLiNhaSach#4]
Hoàn thành Vẽ activity diagrams

**Comment by PIT114203** [comment]
[Activity Diagram.docx](https://github.com/toan203ha/Nhom3_T2_Ca1_QuanLiNhaSach/files/11245236/Activity.Diagram.docx)

**Comment by PIT114203** [comment]
[Uploading Activity Diagram.docx…]()
